Document: librets
Title: Debian librets Manual
Author: <insert document author here>
Abstract: This manual describes what librets is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/librets/librets.sgml.gz

Format: postscript
Files: /usr/share/doc/librets/librets.ps.gz

Format: text
Files: /usr/share/doc/librets/librets.text.gz

Format: HTML
Index: /usr/share/doc/librets/html/index.html
Files: /usr/share/doc/librets/html/*.html
